# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:20.04

pipelines:
  default:
    - step:
        name: 'Build'
        script:
          - apt -y update
          - apt -y install tzdata
          - apt -y install wget lsb-release
          - apt -y install git cmake ninja-build g++ libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libvlc-dev libpng-dev
          - git clone https://bitbucket.org/panreyes/bennugd2.git
          - cd bennugd2
          - ./build.sh linux use_sdl2
